server:
  port: 29999

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/siot
    username: root
    password: black
#    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fordawn.application.dao.entity